// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoJGepOgOnRBF1rH5Hni2Iputp0US-7WM',
    appId: '1:986437984520:web:42ad76192b3e196bc60cbd',
    messagingSenderId: '986437984520',
    projectId: 'download-wallpaper-a9592',
    authDomain: 'download-wallpaper-a9592.firebaseapp.com',
    storageBucket: 'download-wallpaper-a9592.appspot.com',
    measurementId: 'G-6XMB38595N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2hCCI2rgTjaJr18hpdeBM33FJavFVjzE',
    appId: '1:986437984520:android:1e2f47c76c3ac173c60cbd',
    messagingSenderId: '986437984520',
    projectId: 'download-wallpaper-a9592',
    storageBucket: 'download-wallpaper-a9592.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBffsi8ufAUsaJDUzGiiCvB6NopLbb_9RM',
    appId: '1:986437984520:ios:68d2b03e81587531c60cbd',
    messagingSenderId: '986437984520',
    projectId: 'download-wallpaper-a9592',
    storageBucket: 'download-wallpaper-a9592.appspot.com',
    iosBundleId: 'com.hasanur.downloadWallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBffsi8ufAUsaJDUzGiiCvB6NopLbb_9RM',
    appId: '1:986437984520:ios:68d2b03e81587531c60cbd',
    messagingSenderId: '986437984520',
    projectId: 'download-wallpaper-a9592',
    storageBucket: 'download-wallpaper-a9592.appspot.com',
    iosBundleId: 'com.hasanur.downloadWallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoJGepOgOnRBF1rH5Hni2Iputp0US-7WM',
    appId: '1:986437984520:web:aa53476c95aa79d3c60cbd',
    messagingSenderId: '986437984520',
    projectId: 'download-wallpaper-a9592',
    authDomain: 'download-wallpaper-a9592.firebaseapp.com',
    storageBucket: 'download-wallpaper-a9592.appspot.com',
    measurementId: 'G-LDTEMYB96T',
  );
}
